universe = vanilla
executable = process_video.sh
arguments = $(file)
getenv = true

request_GPUs = 0
request_cpus = 16
request_memory = 32G

Output     = /cluster/research-groups/wehrwein/home/allesis/log/output.log
Error      = /cluster/research-groups/wehrwein/home/allesis/log/error.log
Log        = /cluster/research-groups/wehrwein/home/allesis/log/condor.log

initialdir = $HOME/gits/hash-compression
queue file matching *.y4m
